import os
from dotenv import load_dotenv
from modules.instagram_publish import InstagramPublisher, test_instagram_connection

def test_post_to_instagram():
    """Test posting an image to Instagram"""
    # Load environment variables
    load_dotenv()
    
    # First test the connection
    if not test_instagram_connection():
        print("Failed to connect to Instagram. Please check your credentials.")
        return
    
    # Use a local test image
    test_image_path = "haikubg_with_text.jpg"  # This should be generated by your haiku generator
    if not os.path.exists(test_image_path):
        print(f"Test image not found: {test_image_path}")
        print("Please make sure you have a test image file available.")
        return
    
    test_caption = """🤖 AI News Brew Test Post

Testing Instagram integration for AI News Brew.
This is an automated test post.

#AINewsBrew #TestPost #AI #News"""

    try:
        publisher = InstagramPublisher()
        post_id = publisher.publish_post(test_image_path, test_caption)
        
        if post_id:
            print(f"Successfully published test post to Instagram!")
            print(f"Post ID: {post_id}")
        else:
            print("Failed to publish test post to Instagram")
            
    except Exception as e:
        print(f"Error during test: {str(e)}")

if __name__ == "__main__":
    test_post_to_instagram() 